# Generated by Django 5.2.7 on 2025-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='Genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='Pelicula',
            new_name='pelicula',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
